// wc/src/app-widgets.ts
import { html } from 'lit';
import { customElement } from 'lit/decorators.js';
import { clockService, openingsService } from '../../common/service/index.service.ts';
import { MobxLitElement } from '@adobe/lit-mobx';
import { PlayService } from '../../common/service/play.service.ts';
import { ClockService } from '../../common/service/clock.service.ts';
import { css } from 'lit-element';
import { TW_CSS } from './css.ts';
import { AnalyzerService } from '../../common/service/analyzer.service.ts';
import { property } from 'lit-element/decorators.js';
import { RenderingService } from '../../common/service/rendering.service.ts';

@customElement('cb-cp')
export class CP extends MobxLitElement {
  @property({ attribute: true })
  analyzer!: AnalyzerService;
  @property({ attribute: true })
  rendering!: RenderingService;
  static styles = [
    css`
      div {
        width: 32px;
      }
      span {
        writing-mode: vertical-lr;
        margin-right: 0.5rem;
      }
      .black {
        color: white;
        background-color: black;
      }
      .white {
        background-color: white;
        color: black;
      }
    `,
    TW_CSS,
  ];
  render() {
    const { txt, blackTop, h1, h2 } = this.analyzer.getCpInfo();
    const coloring = (black: boolean) => (black ? 'black' : 'white');
    return this.rendering.showCP
      ? html`
          <div class="h-full flex flex-col flex-grow text-lg">
            <span class="text-center ${coloring(!blackTop)}" style="height: ${h1}"> ${txt} </span>
            <span class="text-center ${coloring(blackTop)}" style="height: ${h2}">${txt}</span>
          </div>
        `
      : html``;
  }
}

@customElement('cb-feninfo')
export class FenInfo extends MobxLitElement {
  play!: PlayService;
  render() {
    return html`<p>${openingsService.sanTextLocate(this.play.log)}</p>`;
  }
}

@customElement('cb-playerinfobar')
export class PlayerInfoBar extends MobxLitElement {
  isTop!: boolean;
  play!: PlayService;
  static styles = [
    css`
      p {
        height: 31px;
        padding: 1px 5px 1px 5px;
      }
    `,
    TW_CSS,
  ];
  render() {
    const { other, label, showTicker, banner, isTextRight } = this.play.getPlayerInfo(this.isTop);
    return html`
      <p class="text-xl m-0 ${isTextRight ? ' text-right' : ''}">
        ${label} &lt; ${showTicker ? html`<cb-ticker .clock=${clockService} />` : html`${other}`}
        &gt; ${banner}
      </p>
    `;
  }
}

@customElement('cb-ticker')
export class Ticker extends MobxLitElement {
  clock!: ClockService;
  render() {
    return html`<span>${this.clock.clockText}</span>`;
  }
}

// react/src/app-widgets.tsx
import { observer } from 'mobx-react';
import { AnalyzerService } from '../../common/service/analyzer.service';
import { ClockService } from '../../common/service/clock.service';
import { PlayService } from '../../common/service/play.service';
import { clockService, openingsService } from '../../common/service/index.service';
import React from 'react';
import { RenderingService } from '../../common/service/rendering.service';

export const CP = observer(
  ({ analyzer, rendering }: { analyzer: AnalyzerService; rendering: RenderingService }) => {
    if (!rendering.showCP) {
      return <div className="w-6 h-full flex flex-col flex-grow"></div>;
    }
    const { txt, blackTop, h1, h2 } = analyzer.getCpInfo();
    const coloring = (black: boolean) => (black ? 'bg-black text-white' : 'bg-white text-black');
    return (
      <div className="w-6 h-full flex flex-col flex-grow [&>div]:[writing-mode:vertical-lr] [&>div]:text-center">
        <div className={coloring(!blackTop)} style={{ height: h1 }}>
          {txt}
        </div>
        <div className={coloring(blackTop)} style={{ height: h2 }}>
          {txt}
        </div>
      </div>
    );
  }
);

export const FenInfo = observer(({ play }: { play: PlayService }) => {
  return <p>{openingsService.sanTextLocate(play.log)}</p>;
});

export const PlayerInfoBar = observer(({ isTop, play }: { isTop: boolean; play: PlayService }) => {
  const { other, label, showTicker, banner, isTextRight } = play.getPlayerInfo(isTop);
  return (
    <p className={'h-[31px] text-xl dark:text-white m-0 p-1' + (isTextRight ? ' text-right' : '')}>
      {label} &lt;
      {showTicker ? <Ticker clock={clockService} /> : other} &gt;
      {banner}
    </p>
  );
});

export const Ticker = observer(({ clock }: { clock: ClockService }) => (
  <span>{clock.clockText}</span>
));
