// wc/src/app.ts
import { LitElement, html } from 'lit';
import { customElement } from 'lit/decorators.js';
import {
  editService,
  renderingService,
  playService,
  analyzerService,
  messageService,
  mediaService,
  dashboardService,
  historyService,
  configService,
  refreshService,
  connectService,
} from '../../common/service/index.service.ts';
import packageInfo from '../package.json';
import { action } from 'mobx';
import { TW_CSS, MD_ICONS } from './css.ts';
import { css } from 'lit-element';
import { wcInit } from './wc-init.ts';

@customElement('cb-app')
export class App extends LitElement {
  static {
    wcInit();
  }
  static styles = [
    css`
      :root {
        --md-outlined-button-container-shape: 0px;
        --md-outlined-button-label-text-font: system-ui;
        --md-sys-color-primary: #1d3f3f;
        --md-sys-color-outline: #502121;
      }
      .main {
        width: 1024px;
        height: 748px;
        --tw-bg-opacity: 1;
        background-color: rgb(220 252 231 / var(--tw-bg-opacity));
        :is(.dark .dark:bg-green-900) {
          --tw-bg-opacity: 1;
          background-color: rgb(20 83 45 / var(--tw-bg-opacity));
        }
        border-width: 0px;
      }
      .header {
        height: 32px;
        :is(.dark .dark:text-white) {
          --tw-text-opacity: 1;
          color: rgb(255 255 255 / var(--tw-text-opacity));
        }
      }
      .config {
        width: 900px;
        height: 600px;
      }
      .down {
        display: flex;
        flex-grow: 1;
        flex-direction: column;
      }
      cb\-cp {
        width: 24px;
      }
      cb\-board {
      }
      md\-text\-button {
        height: 32px;
        margin: 0;
        padding: 0;
      }
    `,
    TW_CSS,
  ];

  render() {
    return html`
      ${MD_ICONS}
      <div class="main flex m-0 p-0 flex-row">
        <cb-cp .analyzer=${analyzerService} .config=${configService}></cb-cp>
        <div class="down flex flex-col flex-grow">
          <cb-playerinfobar class="m-0 p-0" .isTop=${true} .play=${playService}></cb-playerinfobar>
          <cb-board
            class="m-0 p-0"
            .analyzer=${analyzerService}
            .edit=${editService}
            .rendering=${renderingService}
            .config=${configService}
            .refresh=${refreshService}
          ></cb-board>
          <cb-playerinfobar class="m-0 p-0" .isTop=${false} .play=${playService}></cb-playerinfobar>
        </div>
        <div class="flex flex-col w-full text-center">
          <h3 class="header text-lg flex flex-row m-0 p-0">
            <md-text-button
              @click=${action(() => messageService.standard('about'))}
              class="text-xl"
            >
              ChessBuddy ${packageInfo.version}
            </md-text-button>
            <md-text-button @click=${action(mediaService.playAllAction)}>
              <span class="material-symbols-outlined">refresh</span>
            </md-text-button>
          </h3>
          <cb-panel .edit=${editService} .dashboard=${dashboardService} .history=${historyService}>
            <cb-feninfo slot="top" .play=${playService}></cb-feninfo>
            <cb-panel-log slot="log" .play=${playService} .history=${historyService}>
            </cb-panel-log>
            <cb-panel-hist slot="hist" .history=${historyService}> </cb-panel-hist>
            <cb-panel-edit slot="edit" .edit=${editService}> </cb-panel-edit>
          </cb-panel>
        </div>
        <cb-message-dialog .message=${messageService}></cb-message-dialog>
        <cb-dialog-mp4 .mp4=${mediaService}></cb-dialog-mp4>
      </div>
      <cb-config-dialog class="config" .config=${configService}>
        <cb-config-game slot="0" .config=${configService}></cb-config-game>
        <cb-config-display
          slot="1"
          .config=${configService}
          .rendering=${renderingService}
        ></cb-config-display>
        <cb-config-clock slot="2" .config=${configService}></cb-config-clock>
        <cb-config-human
          slot="3"
          .config=${configService}
          .connect=${connectService}
        ></cb-config-human>
        <cb-config-bot slot="4" .config=${configService}></cb-config-bot>
        <cb-config-bluetooth slot="5" .config=${configService}></cb-config-bluetooth>
      </cb-config-dialog>
    `;
  }
}

// react/src/App.tsx
/* eslint-disable @typescript-eslint/no-namespace */
import React from 'react';
import { editService, renderingService, clockService } from '../../common/service/index.service';
import {
  playService,
  analyzerService,
  messageService,
  mediaService,
  dashboardService,
  historyService,
  configService,
  refreshService,
  openingsService,
} from '../../common/service/index.service';
import { ConfigDialog } from './ConfigDialog';
import { Board } from './Board';
import { AnalyzerService } from '../../common/service/analyzer.service';
import packageInfo from '../package.json';
import { Mp4Dialog } from './Mp4Dialog';
import { MessageDialog } from './MessageDialog';
import { RenderingService } from '../../common/service/rendering.service';
import { observer } from 'mobx-react';
import { createTheme, ThemeProvider } from '@mui/material/styles';
import CssBaseline from '@mui/material/CssBaseline';
import { MdRefresh } from 'react-icons/md';
import { MainButtonBar } from './MainButtonBar';
import { MainView } from './MainView';
import { ConfigService } from '../../common/service/config.service';
import { PlayService } from '../../common/service/play.service';
import { ClockService } from '../../common/service/clock.service';
import { action } from 'mobx';

const lightTheme = createTheme({
  palette: {
    mode: 'light',
  },
  components: {
    MuiTab: {
      styleOverrides: {
        root: {
          backgroundColor: 'lightgreen',
          '&$selected': {
            backgroundColor: 'blue',
          },
        },
      },
    },
    MuiButton: {
      styleOverrides: {
        root: {
          backgroundColor: 'green',
        },
      },
    },
  },
});

const darkTheme = createTheme({
  palette: {
    mode: 'dark',
  },
  components: {
    MuiTab: {
      styleOverrides: {
        root: {
          backgroundColor: 'darkgreen',
          '&$selected': {
            backgroundColor: 'blue',
          },
        },
      },
    },
    MuiButton: {
      styleOverrides: {
        root: {
          backgroundColor: 'darkgreen',
        },
      },
    },
  },
});

const CP = observer(
  ({ analyzer, config }: { analyzer: AnalyzerService; config: ConfigService }) => {
    if (!config.showCP) {
      return <div className="w-6 h-full flex flex-col flex-grow"></div>;
    }
    const { txt, blackTop, h1, h2 } = analyzer.getCpInfo();
    const coloring = (black: boolean) => (black ? 'bg-black text-white' : 'bg-white text-black');
    return (
      <div className="w-6 h-full flex flex-col flex-grow [&>div]:[writing-mode:vertical-lr] [&>div]:text-center">
        <div className={coloring(!blackTop)} style={{ height: h1 }}>
          {txt}
        </div>
        <div className={coloring(blackTop)} style={{ height: h2 }}>
          {txt}
        </div>
      </div>
    );
  }
);

const Ticker = observer(({ clock }: { clock: ClockService }) => <span>{clock.clockText}</span>);

const PlayerInfoBar = observer(({ isTop, play }: { isTop: boolean; play: PlayService }) => {
  const { other, label, showTicker, banner, isTextRight } = play.getPlayerInfo(isTop);
  return (
    <p className={'h-[31px] text-xl dark:text-white m-0 p-1' + (isTextRight ? ' text-right' : '')}>
      {label} &lt;
      {showTicker ? <Ticker clock={clockService} /> : other} &gt;
      {banner}
    </p>
  );
});

const FenInfo = observer(({ play }: { play: PlayService }) => {
  return <p>{openingsService.sanTextLocate(play.log)}</p>;
});

export const ChessBuddy = observer(({ rendering }: { rendering: RenderingService }) => {
  const about = () => messageService.standard('About');
  const version = packageInfo.version;
  return (
    <ThemeProvider theme={rendering.darkTheme ? darkTheme : lightTheme}>
      <CssBaseline />
      <div className={rendering.darkTheme ? 'dark' : 'light'}>
        <div className="w-[1024px] h-[748px] bg-green-100 dark:bg-green-900 border-0 flex m-0 p-0 flex-row">
          <CP analyzer={analyzerService} config={configService} />
          <div className="flex flex-col flex-grow">
            <PlayerInfoBar isTop={true} play={playService} />
            <Board
              analyzer={analyzerService}
              edit={editService}
              rendering={rendering}
              config={configService}
              refresh={refreshService}
            />
            <PlayerInfoBar isTop={false} play={playService} />
          </div>
          <div className="flex flex-col w-full text-center">
            <h3 className="h-8 text-lg dark:text-white flex flex-row">
              <span onClick={action(about)} className="mx-5 text-xl">
                ChessBuddy {version}
              </span>
              <MdRefresh className="text-lg mx-5" onClick={action(mediaService.playAllAction)} />
            </h3>
            <MainButtonBar
              edit={editService}
              dashboard={dashboardService}
              history={historyService}
            />
            <FenInfo play={playService} />
            <MainView dashboard={dashboardService} edit={editService} />
          </div>
          <MessageDialog message={messageService} />
          <Mp4Dialog mp4={mediaService} />
          <ConfigDialog config={configService} />
        </div>
      </div>
    </ThemeProvider>
  );
});

const App: React.FC = () => <ChessBuddy rendering={renderingService} />;
export default App;
