// wc/src/app.ts
import { LitElement, html } from 'lit';
import { customElement } from 'lit/decorators.js';
import {
  editService,
  renderingService,
  playService,
  analyzerService,
  messageService,
  mediaService,
  dashboardService,
  historyService,
  configService,
  refreshService,
  connectService,
} from '../../common/service/index.service.ts';
import packageInfo from '../package.json';
import { action } from 'mobx';
import { TW_CSS, MD_ICONS } from './css.ts';
import { css } from 'lit-element';
import { wcInit } from './wc-init.ts';

@customElement('cb-app')
export class App extends LitElement {
  static {
    wcInit();
  }
  static styles = [
    css`
      :root {
        --md-outlined-button-container-shape: 0px;
        --md-outlined-button-label-text-font: system-ui;
        --md-sys-color-primary: #1d3f3f;
        --md-sys-color-outline: #502121;
      }
      .main {
        width: 1024px;
        height: 748px;
        --tw-bg-opacity: 1;
        background-color: rgb(220 252 231 / var(--tw-bg-opacity));
        :is(.dark .dark:bg-green-900) {
          --tw-bg-opacity: 1;
          background-color: rgb(20 83 45 / var(--tw-bg-opacity));
        }
        border-width: 0px;
      }
      .header {
        height: 32px;
        :is(.dark .dark:text-white) {
          --tw-text-opacity: 1;
          color: rgb(255 255 255 / var(--tw-text-opacity));
        }
      }
      .config {
        width: 900px;
        height: 600px;
      }
      .down {
        display: flex;
        flex-grow: 1;
        flex-direction: column;
      }
      cb\-cp {
        width: 24px;
      }
      cb\-board {
      }
      md\-text\-button {
        height: 32px;
        margin: 0;
        padding: 0;
      }
    `,
    TW_CSS,
  ];

  render() {
    return html`
      ${MD_ICONS}
      <div class="main flex m-0 p-0 flex-row">
        <cb-cp .analyzer=${analyzerService} .config=${configService}></cb-cp>
        <div class="down flex flex-col flex-grow">
          <cb-playerinfobar class="m-0 p-0" .isTop=${true} .play=${playService}></cb-playerinfobar>
          <cb-board
            class="m-0 p-0"
            .analyzer=${analyzerService}
            .edit=${editService}
            .rendering=${renderingService}
            .config=${configService}
            .refresh=${refreshService}
          ></cb-board>
          <cb-playerinfobar class="m-0 p-0" .isTop=${false} .play=${playService}></cb-playerinfobar>
        </div>
        <div class="flex flex-col w-full text-center">
          <h3 class="header text-lg flex flex-row m-0 p-0">
            <md-text-button
              @click=${action(() => messageService.standard('about'))}
              class="text-xl"
            >
              ChessBuddy ${packageInfo.version}
            </md-text-button>
            <md-text-button @click=${action(mediaService.playAllAction)}>
              <span class="material-symbols-outlined">refresh</span>
            </md-text-button>
            <a href="react.html">wc</a>
          </h3>
          <cb-panel .edit=${editService} .dashboard=${dashboardService} .history=${historyService}>
            <cb-feninfo slot="top" .play=${playService}></cb-feninfo>
            <cb-panel-log slot="log" .play=${playService} .history=${historyService}>
            </cb-panel-log>
            <cb-panel-hist slot="hist" .history=${historyService}> </cb-panel-hist>
            <cb-panel-edit slot="edit" .edit=${editService}> </cb-panel-edit>
          </cb-panel>
        </div>
        <cb-message-dialog .message=${messageService}></cb-message-dialog>
        <cb-dialog-mp4 .mp4=${mediaService}></cb-dialog-mp4>
      </div>
      <cb-config-dialog class="config" .config=${configService}>
        <cb-config-game slot="0" .config=${configService}></cb-config-game>
        <cb-config-display
          slot="1"
          .config=${configService}
          .rendering=${renderingService}
        ></cb-config-display>
        <cb-config-human
          slot="2"
          .config=${configService}
          .connect=${connectService}
        ></cb-config-human>
        <cb-config-bot slot="3" .config=${configService}></cb-config-bot>
        <cb-config-clock slot="4" .config=${configService}></cb-config-clock>
        <cb-config-bluetooth slot="5" .config=${configService}></cb-config-bluetooth>
      </cb-config-dialog>
    `;
  }
}

// react/src/app.tsx
/* eslint-disable @typescript-eslint/no-namespace */
import React from 'react';
import { editService, renderingService } from '../../common/service/index.service';
import {
  playService,
  analyzerService,
  messageService,
  mediaService,
  dashboardService,
  historyService,
  configService,
  refreshService,
} from '../../common/service/index.service';
import packageInfo from '../package.json';
import { Mp4dialog } from './mp4dialog';
import { RenderingService } from '../../common/service/rendering.service';
import { observer } from 'mobx-react';
import { createTheme, ThemeProvider } from '@mui/material/styles';
import CssBaseline from '@mui/material/CssBaseline';
import { MdRefresh } from 'react-icons/md';
import { PanelButtonbar } from './panel-buttonbar';
import { Panel } from './panel';
import { action } from 'mobx';
import { ConfigDialog } from './config-dialog';
import { MessageDialog } from './message-dialog';
import { Board } from './board';
import { CP, FenInfo, PlayerInfoBar } from './app-widgets';

const lightTheme = createTheme({
  palette: {
    mode: 'light',
  },
  components: {
    MuiTab: {
      styleOverrides: {
        root: {
          backgroundColor: 'lightgreen',
          '&$selected': {
            backgroundColor: 'blue',
          },
        },
      },
    },
    MuiButton: {
      styleOverrides: {
        root: {
          backgroundColor: 'green',
        },
      },
    },
  },
});

const darkTheme = createTheme({
  palette: {
    mode: 'dark',
  },
  components: {
    MuiTab: {
      styleOverrides: {
        root: {
          backgroundColor: 'darkgreen',
          '&$selected': {
            backgroundColor: 'blue',
          },
        },
      },
    },
    MuiButton: {
      styleOverrides: {
        root: {
          backgroundColor: 'darkgreen',
        },
      },
    },
  },
});
export const ChessBuddy = observer(({ rendering }: { rendering: RenderingService }) => {
  const version = packageInfo.version;
  return (
    <ThemeProvider theme={rendering.darkTheme ? darkTheme : lightTheme}>
      <CssBaseline />
      <div className={rendering.darkTheme ? 'dark' : 'light'}>
        <div className="w-[1024px] h-[748px] bg-green-100 dark:bg-green-900 border-0 flex m-0 p-0 flex-row">
          <CP analyzer={analyzerService} config={configService} />
          <div className="flex flex-col flex-grow">
            <PlayerInfoBar isTop={true} play={playService} />
            <Board
              analyzer={analyzerService}
              edit={editService}
              rendering={rendering}
              config={configService}
              refresh={refreshService}
            />
            <PlayerInfoBar isTop={false} play={playService} />
          </div>
          <div className="flex flex-col w-full text-center">
            <h3 className="h-8 text-lg dark:text-white flex flex-row">
              <span
                onClick={action(() => messageService.standard('about'))}
                className="mx-5 text-xl"
              >
                ChessBuddy {version}
              </span>
              <MdRefresh className="text-lg mx-5" onClick={action(mediaService.playAllAction)} />
              <a href="wc.html">react</a>
            </h3>
            <PanelButtonbar
              edit={editService}
              dashboard={dashboardService}
              history={historyService}
            />
            <FenInfo play={playService} />
            <Panel dashboard={dashboardService} edit={editService} />
          </div>
          <MessageDialog message={messageService} />
          <Mp4dialog mp4={mediaService} />
          <ConfigDialog config={configService} />
        </div>
      </div>
    </ThemeProvider>
  );
});

const App: React.FC = () => <ChessBuddy rendering={renderingService} />;
export default App;
