// wc/src/config-game.ts
import { MobxLitElement } from '@adobe/lit-mobx';
import { html } from 'lit';
import { customElement } from 'lit/decorators.js';
import { playService } from '../../common/service/index.service';
import { action } from 'mobx';
import { ConfigButton, ConfigSelect } from './config-widgets';
import { ConfigService } from '../../common/service/config.service';
import { STYLES } from './css';

@customElement('cb-config-game')
export class ConfigGame extends MobxLitElement {
  config!: ConfigService;

  render() {
    const players = [...this.config.humans, ...this.config.bots];
    console.log(players);
    const playerNames = Array.from(players.map(x => x.getName()));
    console.log(playerNames);
    new ConfigSelect();
    new ConfigButton();

    return html`${STYLES}
      <style>
        .main {
          width: 1000px;
          height: 400px;
        }
        .buttons {
          margin-left: 0.5rem;
          margin-right: 0.5rem;
        }
      </style>
      <div class="main text-left flex flex-col">
        <cb-config-select
          label="White"
          id="white"
          .choices=${playerNames}
          .props=${this.config.properties}
        ></cb-config-select>
        <cb-config-select
          label="Black"
          id="black"
          .choices=${playerNames}
          .props=${this.config.properties}
        ></cb-config-select>
        <cb-config-select
          class=""
          label="Timer setting"
          id="clock"
          .choices=${this.config.clocks.map(x => x.name)}
          .props=${this.config.properties}
        ></cb-config-select>
        <div>&nbsp;</div>
        <div class="buttons">
          <cb-config-button
            .onClick=${action(playService.startGameAction)}
            label="Play"
            icon="play_circle"
          ></cb-config-button>
          <cb-config-button
            .onClick=${action(playService.endGameAction)}
            label="End game"
            icon="exit_to_app"
            .disabled=${playService.isComplete}
          ></cb-config-button>
          <cb-config-button
            .onClick=${action(playService.resetGameAction)}
            label="Reset"
            icon="clear"
          ></cb-config-button>
          <cb-config-button
            .onClick=${action(playService.editGameAction)}
            label="Edit"
            icon="edit"
          ></cb-config-button>
        </div>
      </div> `;
  }
}

// react/src/config-game.tsx
import React from 'react';
import { MdExitToApp, MdPlayCircle, MdClear, MdEdit } from 'react-icons/md';
import { observer } from 'mobx-react';
import { ConfigService } from '../../common/service/config.service';
import { playService } from '../../common/service/index.service';
import { action } from 'mobx';
import { ConfigButton, ConfigSelect } from './config-widgets';

export const ConfigGame = observer(({ config }: { config: ConfigService }) => {
  const players = [...config.humans, ...config.bots];
  const playerNames = Array.from(players.map(x => x.getName()));
  const item = config.game;

  return (
    <div className="w-[800px] h-[400px] flex flex-col text-center [&>div]:text-left">
      <div>
        <ConfigSelect label="White" id="white" choices={playerNames} item={item} />
        &nbsp;
        <ConfigSelect label="Black" choices={playerNames} id="black" item={item} />
      </div>
      <div>&nbsp;</div>
      <ConfigSelect
        label="Timer setting"
        id="clock"
        choices={config.clocks.map(x => x.name)}
        item={item}
      />
      <div>&nbsp;</div>
      <div className="[&>button]:mx-2">
        <ConfigButton
          onClick={action(playService.startGameAction)}
          label="Play"
          icon={<MdPlayCircle />}
        />
        <ConfigButton
          onClick={action(playService.endGameAction)}
          label="End game"
          icon={<MdExitToApp />}
          disabled={playService.isComplete}
        />
        <ConfigButton
          onClick={action(playService.resetGameAction)}
          label="Reset"
          icon={<MdClear />}
        />
        <ConfigButton onClick={action(playService.editGameAction)} label="Edit" icon={<MdEdit />} />
      </div>
    </div>
  );
});
