// wc/src/main-button-bar.ts
import { html } from 'lit';
import { customElement } from 'lit/decorators.js';
import { MdTabs } from '@material/web/tabs/tabs.js';
import { MdPrimaryTab } from '@material/web/tabs/primary-tab.js';
import { playService, configService } from '../../common/service/index.service';
import { MobxLitElement } from '@adobe/lit-mobx';
import { action } from 'mobx';
import { HistoryService } from '../../common/service/history.service';
import { DashboardService } from '../../common/service/dashboard.service';
import { EditService } from '../../common/service/edit.service';
import { STYLES } from './css';

@customElement('cb-mainbuttonbar')
export class MainButtonBar extends MobxLitElement {
  edit!: EditService;
  dashboard!: DashboardService;
  history!: HistoryService;
  render() {
    new MdTabs();
    new MdPrimaryTab();
    const isGotoHist = this.dashboard.showHist && this.history.markHist >= 0;
    const isHistUndo = !this.dashboard.showHist && this.dashboard.markLog >= 0;
    const isPlayUndo = playService.isPlaying && this.dashboard.showUndo;
    const button1 =
      isHistUndo || isPlayUndo ? 'undo' : playService.isPlaying ? 'play_arrow' : 'pause';
    const button2 = isGotoHist
      ? this.edit.showEdit
        ? 'input'
        : 'edit'
      : this.dashboard.showHist
        ? 'folder_open'
        : 'history';

    return html`
      ${STYLES}
      <md-tabs color="primary" aria-label="outlined primary button group" class="w-full">
        <md-primary-tab @click=${action(playService.playButtonAction)}>
          <span class="text-3xl material-symbols-outlined">${button1}</span>
        </md-primary-tab>
        <md-primary-tab @click=${action(this.dashboard.toggleHistoryAction)}>
          <span class="text-3xl material-symbols-outlined">${button2}</span>
        </md-primary-tab>
        <md-primary-tab @click=${action(configService.openConfigAction)}>
          <span class="text-3xl material-symbols-outlined">settings</span>
        </md-primary-tab>
      </md-tabs>
    `;
  }
}

// react/src/MainButtonBar.tsx
import React, { ReactElement } from 'react';
import { Button, ButtonGroup } from '@mui/material';
import { observer } from 'mobx-react';
import { playService, configService } from '../../common/service/index.service';
import { DashboardService } from '../../common/service/dashboard.service';
import {
  MdInput,
  MdOutlineFolderOpen,
  MdOutlineHistory,
  MdPause,
  MdPlayArrow,
  MdSettings,
  MdUndo,
  MdEdit,
} from 'react-icons/md';
import { HistoryService } from '../../common/service/history.service';
import { EditService } from '../../common/service/edit.service';
import { action } from 'mobx';

export const MainButtonBar = observer(
  ({
    dashboard,
    edit,
    history,
  }: {
    dashboard: DashboardService;
    edit: EditService;
    history: HistoryService;
  }) => {
    const isGotoHist = dashboard.showHist && history.markHist >= 0;
    const isHistUndo = !dashboard.showHist && dashboard.markLog >= 0;
    const isPlayUndo = playService.isPlaying && dashboard.showUndo;

    const PanelButton = (props: { children: ReactElement; onClick: () => void }) => (
      <Button
        className="h-14 flex-grow bg-green-700"
        sx={{ backgroundColor: 'darkgreen' }}
        onClick={action(props.onClick)}
        variant="contained"
      >
        {props.children}
      </Button>
    );

    return (
      <ButtonGroup color="primary" aria-label="outlined primary button group" className="w-full">
        <PanelButton onClick={action(playService.playButtonAction)}>
          {isHistUndo || isPlayUndo ? (
            <MdUndo className="text-3xl" />
          ) : playService.isPlaying ? (
            <MdPlayArrow className="text-3xl" />
          ) : (
            <MdPause className="text-3xl" />
          )}
        </PanelButton>
        <PanelButton onClick={action(dashboard.toggleHistoryAction)}>
          {isGotoHist ? (
            <MdInput className="text-3xl" />
          ) : edit.showEdit ? (
            <MdEdit className="text-3xl" />
          ) : dashboard.showHist ? (
            <MdOutlineFolderOpen className="text-3xl" />
          ) : (
            <MdOutlineHistory className="text-3xl" />
          )}
        </PanelButton>
        <PanelButton onClick={action(configService.openConfigAction)}>
          <MdSettings className="text-3xl" />
        </PanelButton>
      </ButtonGroup>
    );
  }
);
