// wc/src/panel-hist.ts
import { MobxLitElement } from '@adobe/lit-mobx';
import { html } from 'lit';
import { customElement } from 'lit/decorators.js';
import { HistoryService } from '../../common/service/history.service';
import { GridWidget } from './main-widgets';
import { STYLES } from './css';

@customElement('cb-panel-hist')
export class PanelHist extends MobxLitElement {
  history!: HistoryService;
  render() {
    new GridWidget();
    const historyClick = (event: MouseEvent) => {
      event.preventDefault();
      const id = Number.parseInt(
        ((event.target as HTMLTableCellElement).parentNode as HTMLTableRowElement).id
      );
      this.history.setMarkHist(id == this.history.markHist ? -1 : id);
    };

    return html`
      ${STYLES}
      <cb-grid .onClickAction=${historyClick} .scroll=${this.history.markHist == -1}>
        ${this.history.getGames().map((row, iRow) => {
          const { time, win, c1, c2 } = row;
          const marker = iRow == this.history.markHist ? ' bg-green-300' : '';
          return html`<tr
            key=${iRow.toString()}
            id=${iRow.toString()}
            class="[&td]:p-[3px] [&td]:text-center [&td]:text-lg dark:text-white ${marker}"
          >
            <td>${time}</td>
            <td>${c1}</td>
            <td>${c2}</td>
            <td>${win}</td>
          </tr>`;
        })}
      </cb-grid>
    `;
  }
}

// react/src/panel-hist.tsx
import React, { MouseEvent } from 'react';
import { observer } from 'mobx-react';
import { HistoryService } from '../../common/service/history.service';
import { GridWidget } from './main-widgets';

export const PanelHist = observer(({ history }: { history: HistoryService }) => {
  const historyClick = (event: MouseEvent<HTMLTableElement>) => {
    event.preventDefault();
    const id = Number.parseInt(
      ((event.target as HTMLTableCellElement).parentNode as HTMLTableRowElement).id
    );
    history.setMarkHist(id == history.markHist ? -1 : id);
  };

  const tableRows = history.getGames().map((row, iRow) => {
    const { time, win, c1, c2 } = row;
    const marker = iRow == history.markHist ? ' bg-green-300' : '';
    return (
      <tr
        key={iRow.toString()}
        id={iRow.toString()}
        className={'[&td]:p-[3px] [&td]:text-center [&td]:text-lg dark:text-white' + marker}
      >
        <td>{time}</td>
        <td>{c1}</td>
        <td>{c2}</td>
        <td>{win}</td>
      </tr>
    );
  });

  return (
    <GridWidget onClickAction={historyClick} scroll={history.markHist == -1}>
      {tableRows}
    </GridWidget>
  );
});
