// react/src/ConfigDialog.tsx
import React, { ChangeEvent, MouseEvent, ReactElement } from 'react';
import { Box, Dialog, Tab, Tabs, Typography } from '@mui/material';
import { ConfigGame } from './ConfigGame';
import { ConfigHuman } from './ConfigHuman';
import { ConfigDisplay } from './ConfigDisplay';
import { ConfigBot } from './ConfigBot';
import { connectService, renderingService } from '../../common/service/index.service';
import { observer } from 'mobx-react';
import { ConfigService } from '../../common/service/config.service';
import { FaChess, FaClock, FaConnectdevelop, FaRobot } from 'react-icons/fa';
import { MdMonitor, MdPeople } from 'react-icons/md';
import { ConfigClock } from './ConfigClock';
import { ConfigBluetooth } from './ConfigBluetooth';
import { action } from 'mobx';

export const ConfigDialog = observer(({ config }: { config: ConfigService }) => {
  const TabPanel = (props: { children: ReactElement; index: number }) => {
    const { children, index } = props;
    return (
      <div
        role="tabpanel"
        hidden={config.showTab !== index}
        id={`nav-tabpanel-${index}`}
        aria-labelledby={`nav-tab-${index}`}
        className="dark:bg-green-900 dark:text-white"
      >
        {config.showTab === index && (
          <Box p={3}>
            <Typography>{children}</Typography>
          </Box>
        )}
      </div>
    );
  };

  // eslint-disable-next-line
  const handleChange = (event: ChangeEvent<{}>, newValue: number) =>
    config.switchTab(newValue as number);

  const prevent = (event: MouseEvent<HTMLAnchorElement>) => event.preventDefault();

  return (
    <Dialog
      aria-labelledby="simple-dialog-title"
      open={config.showConfig}
      onClose={action(config.closeConfigAction)}
      maxWidth="xl"
      className={'text-center text-xl'}
    >
      <Tabs
        value={config.showTab}
        onChange={handleChange}
        aria-label="Settings"
        variant="fullWidth"
      >
        <Tab
          component="a"
          onClick={prevent}
          label={<div className="text-xl">Game</div>}
          icon={<FaChess className="text-3xl" />}
          iconPosition="start"
          id="nav-tab-0"
        />
        <Tab
          component="a"
          onClick={prevent}
          label={<div className="text-xl">Display</div>}
          icon={<MdMonitor className="text-3xl" />}
          iconPosition="start"
          id="nav-tab-1"
        />
        <Tab
          component="a"
          onClick={prevent}
          label={<div className="text-xl">Humans</div>}
          icon={<MdPeople className="text-3xl" />}
          iconPosition="start"
          id="nav-tab-2"
        />
        <Tab
          component="a"
          onClick={prevent}
          label={<div className="text-xl">Bots</div>}
          icon={<FaRobot className="text-3xl" />}
          iconPosition="start"
          id="nav-tab-3"
        />
        <Tab
          component="a"
          onClick={prevent}
          label={<div className="text-xl">Clocks</div>}
          icon={<FaClock className="text-3xl" />}
          iconPosition="start"
          id="nav-tab-4"
        />
        <Tab
          component="a"
          onClick={prevent}
          label={<div className="text-xl">Bluetooth</div>}
          icon={<FaConnectdevelop className="text-3xl" />}
          iconPosition="start"
          id="nav-tab-5"
        />
      </Tabs>
      <TabPanel index={0}>
        <ConfigGame config={config} />
      </TabPanel>
      <TabPanel index={1}>
        <ConfigDisplay config={config} rendering={renderingService} />
      </TabPanel>
      <TabPanel index={2}>
        <ConfigHuman config={config} connect={connectService} />
      </TabPanel>
      <TabPanel index={3}>
        <ConfigBot config={config} />
      </TabPanel>
      <TabPanel index={4}>
        <ConfigClock config={config} />
      </TabPanel>
      <TabPanel index={5}>
        <ConfigBluetooth config={config} />
      </TabPanel>
    </Dialog>
  );
});

// wc/src/config-dialog.ts
import { html } from 'lit';
import { customElement } from 'lit/decorators.js';
import { MdTabs } from '@material/web/tabs/tabs.js';
import { MdPrimaryTab } from '@material/web/tabs/primary-tab.js';
import { MobxLitElement } from '@adobe/lit-mobx';
import { action, runInAction } from 'mobx';
import { ConfigService } from '../../common/service/config.service';
import { MdDialog } from '@material/web/dialog/dialog';
import { STYLES } from './css';

@customElement('cb-config-dialog')
export class ConfigDialog extends MobxLitElement {
  config!: ConfigService;

  render() {
    console.log('config ' + this.config.showConfig);
    if (!this.config.showConfig) {
      return '';
    }

    new MdDialog();
    new MdTabs();
    new MdPrimaryTab();

    const choose = (event: MouseEvent) => {
      event.preventDefault();
      const target = event?.target;
      if (target) {
        const num = event?.target?.id;
        runInAction(() => {
          this.config.switchTab(+num);
        });
        const daddy = target.parentNode.parentNode;
        daddy.childNodes.forEach(child => {
          const slot = child.firstChild;
          if (slot?.name == num) {
            const assigned = slot.assignedElements();
            assigned.forEach(tab => {
              tab.requestUpdate();
            });
          }
        });
      }
    };

    const tab = (num: number, icon: string, title: string) => {
      return html`<md-primary-tab
        class="text-3xl"
        id=${num}
        @click=${choose}
        .active=${num === this.config.showTab}
      >
        <span class="text-lg material-symbols-outlined">${icon}</span>${title}</md-primary-tab
      >`;
    };

    const i = this.config.showTab;
    let j = 0;
    const show = () => (i == j++ ? '' : 'hidden');

    return html`
      ${STYLES}
      <style>
        .main {
          width: 1100px;
          height: 600px;
        }
        .hidden {
          display: none;
        }
      </style>
      <md-dialog
        class="main"
        aria-labelledby="simple-dialog-title"
        open
        @close=${action(this.config.closeConfigAction)}
        maxWidth="xl"
      >
        <form slot="content" id="form-id" method="dialog">
          <md-tabs class="text-lg text-center w-full">
            ${tab(0, 'chess', 'Game')} ${tab(1, 'monitor', 'Display')} ${tab(2, 'people', 'Humans')}
            ${tab(3, 'robot', 'Bots')} ${tab(4, 'av_timer', 'Clocks')}
            ${tab(5, 'bluetooth', 'Bluetooth')}
          </md-tabs>
          <div class=${show()}><slot name="0"></slot></div>
          <div class=${show()}><slot name="1"></slot></div>
          <div class=${show()}><slot name="2"></slot></div>
          <div class=${show()}><slot name="3"></slot></div>
          <div class=${show()}><slot name="4"></slot></div>
          <div class=${show()}><slot name="5"></slot></div>
        </form>
      </md-dialog>
    `;
  }
}
