// react/src/config-lists.tsx
import React, { ReactNode, MouseEvent } from 'react';
import {
  Dialog,
  DialogActions,
  DialogContent,
  DialogContentText,
  DialogTitle,
} from '@mui/material';
import { MdAdd, MdDelete, MdEdit, MdSave } from 'react-icons/md';
import { ListMode, ListType } from '../../common/service/config.service';
import { configService } from '../../common/service/index.service';
import { action } from 'mobx';
import { ConfigButton } from './config-widgets';
import { Item } from '../../common/model/model';

export const ConfigListTable: React.FC<{
  items: Item[];
  onSelect: (id: string) => void;
  cursor: number;
}> = ({ items, onSelect, cursor }) => {
  const onClick = (event: MouseEvent<HTMLTableSectionElement>) => {
    if (event.target instanceof HTMLTableCellElement) {
      onSelect((event.target.parentNode as HTMLTableRowElement).id);
    }
  };
  return (
    <table className="m-1 text-left text-xl dark:bg-slate-800 border-2 border-separate p-2">
      <tbody onClick={onClick}>
        {items.map((item, iLine) => (
          <tr
            key={iLine.toString()}
            id={iLine.toString()}
            className={iLine == cursor ? 'bg-green-300 dark:bg-green-700' : ''}
          >
            <td className="dark:text-white">{item.getName()}</td>
            <td className="dark:text-white">{item.getDescription()}</td>
          </tr>
        ))}
      </tbody>
    </table>
  );
};

export const ConfigListButtons: React.FC<{
  type: ListType;
  children?: React.ReactNode;
}> = ({ type, children }) => {
  const { hasSelect, onDelete, onAdd, onEdit } = configService.getListLogic(type);
  return (
    <div className="[&>button]:mx-1">
      <ConfigButton onClick={onAdd} label="Add" icon={<MdAdd />} />
      <ConfigButton onClick={onEdit} label="Edit" icon={<MdEdit />} disabled={!hasSelect} />
      <ConfigButton onClick={onDelete} label="Delete" icon={<MdDelete />} disabled={!hasSelect} />
      {children}
    </div>
  );
};

export const ConfigPopup: React.FC<{
  type: ListType;
  show: boolean;
  onSave: () => void;
  children?: React.ReactNode;
}> = ({ type, show, onSave, children }) => {
  if (!show) {
    return <div></div>;
  }

  const listProps = configService.ListTypes.get(type);
  const typeName = listProps?.title;
  const isEdit = configService.isEdit();
  const label = (isEdit ? 'Save ' : 'Add ') + typeName;
  const icon = isEdit ? <MdSave /> : <MdAdd />;
  const title = (isEdit ? 'Edit ' : 'Add ') + typeName;
  const onClose = action(() => {
    configService.setListModeAction(ListMode.None);
  });
  return (
    <Dialog aria-labelledby="message" onClose={onClose} className="text-center text-lg" open>
      <DialogTitle id="message">{title}</DialogTitle>
      <DialogContent>
        <DialogContentText>{children}</DialogContentText>
      </DialogContent>
      <DialogActions>
        <ConfigButton onClick={onSave} label={label} icon={icon} />
      </DialogActions>
    </Dialog>
  );
};

// wc/src/config-lists.ts
import { html } from 'lit';
import { customElement } from 'lit/decorators.js';
import { configService } from '../../common/service/index.service';
import { ListMode, ListType } from '../../common/service/config.service';
import { action } from 'mobx';
import { property } from 'lit-element/decorators.js';
import { MD_ICONS, TW_CSS } from './css';
import { css, LitElement } from 'lit-element';
import {Item} from "../../common/model/model.ts";

export const LIST_CSS = css`
  .div {
    width: 800px;
    height: 400px;
    cb\-table\-list,
    cb\-config\-button {
      // mx-1
      margin-left: 0.25rem;
      margin-right: 0.25rem;
    }
  }
  mx\-2 {
    // mx-2
    margin-left: 0.5rem;
    margin-right: 0.5rem;
  }
`;

@customElement('cb-config-list')
export class ConfigList extends LitElement {
  @property({
    hasChanged(newVal: Item[], oldVal: Item[]) {
      return JSON.stringify(newVal) !== JSON.stringify(oldVal);
    },
  })
  items!: Item[];
  onSelect!: (id: string) => void;
  @property({ type: Number })
  cursor!: number;

  selectHandler = (event: Event) => {
    const target = event.target as HTMLElement;
    if (target.nodeName === 'TD') {
      this.onSelect((target.parentNode as HTMLElement).id);
    }
  };

  static styles = [
    css`
      .mark {
        --tw-bg-opacity: 1;
        background-color: rgb(134 239 172 / var(--tw-bg-opacity));
      }
    `,
    TW_CSS,
  ];

  render() {
    return html`
      <table
        class="m-1 text-left text-xl dark:bg-slate-800 border-2 border-separate p-2"
        @click=${this.selectHandler}
      >
        <tbody>
          ${this.items.map(
            (item, iLine) => html`
              <tr id=${iLine.toString()} class="${iLine == this.cursor ? 'mark' : ''}">
                <td class="dark:text-white">${item.getName()}</td>
                <td class="dark:text-white">${item.getDescription()}</td>
              </tr>
            `
          )}
        </tbody>
      </table>
    `;
  }
}

@customElement('cb-config-popup')
export class ConfigPopup extends LitElement {
  type!: ListType;
  @property({ attribute: true })
  show!: boolean;
  @property({ attribute: true })
  onSave!: () => void;

  static styles = [css``, TW_CSS];
  render() {
    if (!this.show) {
      return html``;
    }
    const listProps = configService.ListTypes.get(this.type);
    const typeName = listProps?.title;
    const isEdit = configService.isEdit();
    const label = (isEdit ? 'Save ' : 'Add ') + typeName;
    const icon = isEdit ? 'save' : 'add';
    const title = (isEdit ? 'Edit ' : 'Add ') + typeName;
    const onClose = action(() => {
      configService.setListMode(ListMode.None);
    });
    return html`
      ${MD_ICONS}
      <md-dialog aria-labelledby="message" @close=${onClose} class="text-center text-lg" open>
        <div slot="headline">${title}</div>
        <form slot="content" id="form-id" method="dialog">
          <slot></slot>
          <cb-config-button .onClick=${this.onSave} label=${label} icon=${icon}></cb-config-button>
        </form>
      </md-dialog>
    `;
  }
}
