// src/view/MainView.tsx
import React from 'react';
import { DashboardService } from '../service/dashboard.service';
import { observer } from 'mobx-react';
import { historyService, playService } from '../service/index.service';
import { MainHistoryView as MainHistoryView } from './MainHistoryView';
import { MainLogView as MainLogView } from './MainLogView';
import { MainEditView as MainEditView } from './MainEditView';

export const MainView = observer(({ dashboard }: { dashboard: DashboardService }) => {
  return dashboard.showEdit ? (
    <MainEditView dashboard={dashboard} />
  ) : dashboard.showHist ? (
    <MainHistoryView history={historyService} />
  ) : (
    <MainLogView play={playService} history={historyService} />
  );
});

// wc/src/main-view.ts
import { MobxLitElement } from '@adobe/lit-mobx';
import { html } from 'lit';
import { customElement } from 'lit/decorators.js';
import { DashboardService } from '../../common/service/dashboard.service';
import { EditService } from '../../common/service/edit.service';
import { playService, historyService } from '../../common/service/index.service';
import { MainLogView } from './main-view-log';
import { MainHistoryView } from './main-view-history';
import { MainEditView } from './main-view-edit';
import { STYLES } from './css';
import { autorun } from 'mobx';

@customElement('cb-mainview')
export class MainView extends MobxLitElement {
  edit!: EditService;
  dashboard!: DashboardService;

  render() {
    const i = this.edit.showEdit ? 2 : this.dashboard.showHist ? 1 : 0;
    let j = 0;
    const show = () => (i == j++ ? '' : 'hidden');
    return html`
      <style>
        .hidden {
          display: none;
        }
      </style>
      <div class=${show()}><slot name="0"></slot></div>
      <div class=${show()}><slot name="1"></slot></div>
      <div class=${show()}><slot name="2"></slot></div>
    `;
  }
}
