// old/view/MessageDialog.tsx
import React, { MouseEvent, ReactNode } from 'react';
import {
  Dialog,
  DialogActions,
  DialogContent,
  DialogContentText,
  DialogTitle,
  Link,
} from '@mui/material';
import { observer } from 'mobx-react';
import { MessageService } from '../service/message.service';
import { ButtonType, ConfigButton } from './ConfigWidgets';
import {
  FaChessQueen,
  FaChessRook,
  FaChessKnight,
  FaChessBishop,
  FaChessKing,
  FaRegHandshake,
} from 'react-icons/fa';
import { MdCheck, MdCancel } from 'react-icons/md';
import { action } from 'mobx';

declare global {
    namespace JSX {
        interface IntrinsicElements {
            "md-dialog": {
                open: any,
                type: string,
            };
            "md-text-button": React.DetailedHTMLProps<React.HTMLAttributes<HTMLElement>, HTMLElement>;
        }
    }
}

export const MessageDialog = observer(({ message }: { message: MessageService }) => (
  <md-dialog
      open=""
      type="alert"
    aria-labelledby="message"
//    open={message.title != undefined}
//    onClose={action((e: MouseEvent) => message.onClose((e.target as HTMLButtonElement).innerHTML))}
    className="text-center text-lg">
    <div slot="headline">{message.title}</div>
    <form slot="content" id="form-id" method="dialog">
      {message.msg}
    </form>
    <div slot="actions">
      {message.buttons?.map(x => (
          <md-text-button
//              key={x.label}
//              form="form-id"
//              onClick={action((e: MouseEvent) =>
//                  message.onClose((e.target as HTMLButtonElement).innerHTML)
//              )}
//              icon={x.icon}
          >{x.label}</md-text-button>
      ))}
    </div>
  </md-dialog>
));

export const OK_BUTTON: () => ButtonType[] = () => [{ label: 'Ok' }];
export const YESNO_BUTTONS: () => ButtonType[] = () => [
  { label: 'Yes', icon: <MdCheck /> },
  { label: 'No', icon: <MdCancel /> },
];
export const PROMOTE_BUTTONS: () => ButtonType[] = () => [
  { label: 'Queen', icon: <FaChessQueen /> },
  { label: 'Rook', icon: <FaChessRook /> },
  { label: 'Knight', icon: <FaChessKnight /> },
  { label: 'Bishop', icon: <FaChessBishop /> },
];

export const WINNER_BUTTONS: (black: string, white: string) => ButtonType[] = (black, white) => [
  { label: white, icon: <FaChessKing className="text-white" /> },
  { label: 'Draw', icon: <FaRegHandshake /> },
  { label: black, icon: <FaChessKing className="text-black" /> },
];

export const WINNER_HTML: ReactNode = (
  <div className="text-3xl">
    Who won?
    <img src="/png/win.png" />
  </div>
);

export const ABOUT: ReactNode = (
  <div>
    This chess program is open source and available at github.
    <ul>
      <li>
        <Link href="https://github.com/pdigre/chessbuddy" target="_blank" rel="noopener">
          Github pdigre/chessbuddy
        </Link>
      </li>
      <li>
        <Link
          href="https://github.com/pdigre/chessbuddy/wiki/User-guide"
          target="_blank"
          rel="noopener">
          User Guide / instructions
        </Link>
      </li>
    </ul>
  </div>
);

// wc/src/message-dialog.ts
import { MobxLitElement } from '@adobe/lit-mobx';
import { PropertyValueMap, html } from 'lit';
import { customElement, property } from 'lit/decorators.js';
import { MdDialog } from '@material/web/dialog/dialog';
import { MessageService, messageType } from '../../common/service/message.service';
import { action } from 'mobx';
import { TW_CSS, MD_ICONS } from './css';
import { css, TemplateResult } from 'lit-element';
import { SVG_DRAW, SVG_KING } from './svg';
import { configService } from '../../common/service/index.service';

@customElement('cb-message-dialog')
export class MessageDialog extends MobxLitElement {
  @property({ attribute: false })
  public message!: MessageService;
  public title = '';
  public msg = '';
  public buttons: ButtonType[] = [];
  public clicked = '';

  static styles = [css``, TW_CSS];

  public render(): TemplateResult {
    const onClick = action((e: MouseEvent) => (this.clicked = (e.target as HTMLElement).className));
    return html`
      ${MD_ICONS}
      <md-dialog
        id="message-dialog"
        type="alert"
        aria-labelledby="message"
        .open=${this.message.show}
        class="text-center text-lg"
      >
        <div slot="headline">${this.title}</div>
        <form slot="content" id="form-id" method="dialog">${getMsg(this.msg)}</form>
        <div slot="actions">${this.buttons?.map(x => this.renderButton(x, onClick))}</div>
      </md-dialog>
    `;
  }
  private renderButton(x: ButtonType, onClick: (e: MouseEvent) => void) {
    switch (x.type ?? '') {
      case 'text':
        return html`${x.custom ?? ''}
          <md-text-button class="${x.name}" form="form-id" @click=${onClick}
            >${x.icon ? html`<span class="material-symbols-outlined">${x.icon ?? ''}</span>` : ''}
            ${x.html ?? ''}${x.label}</md-text-button
          >`;
      case 'tonal':
        return html`${x.custom ?? ''}
          <md-filled-tonal-button class="${x.name}" form="form-id" @click=${onClick}
            >${x.icon ? html`<span class="material-symbols-outlined">${x.icon ?? ''}</span>` : ''}
            ${x.html ?? ''}${x.label}</md-filled-tonal-button
          >`;
      case 'outlined':
        return html`${x.custom ?? ''}
          <md-outlined-button class="${x.name}" form="form-id" @click=${onClick}
            >${x.icon ? html`<span class="material-symbols-outlined">${x.icon ?? ''}</span>` : ''}
            ${x.html ?? ''}${x.label}</md-outlined-button
          >`;
      default:
        return html`${x.custom ?? ''}
          <md-filled-button class="${x.name}" form="form-id" @click=${onClick}
            >${x.icon ? html`<span class="material-symbols-outlined">${x.icon ?? ''}</span>` : ''}
            ${x.html ?? ''}${x.label}</md-filled-button
          >`;
    }
  }
  protected updated(_changedProperties: PropertyValueMap<any> | Map<PropertyKey, unknown>): void {
    const dialog = this.shadowRoot!.getElementById('message-dialog') as MdDialog;
    const func = (msg: messageType) => {
      this.title = msg.title;
      this.msg = msg.msg;
      this.buttons = getButtons(msg.name);
      const THIS = this;
      dialog.show();
      dialog.requestUpdate();
      dialog.addEventListener('closed', function listener() {
        dialog.removeEventListener('closed', listener);
        if (msg.callback) {
          msg.callback(THIS.clicked);
        }
      });
    };

    this.message.initialize(func);
  }
}

function getButtons(name: string): ButtonType[] {
  switch (name) {
    case 'about':
    case 'load':
      return [{ name: 'ok', label: 'Ok' }];
    case 'undo':
    case 'revert':
      return [
        { name: 'y', label: 'Yes', icon: 'check' },
        { name: 'n', label: 'No', icon: 'cancel', type: 'tonal' },
      ];
    case 'promotion':
      return [
        { name: 'q', label: 'Queen', icon: 'FaChessQueen' },
        { name: 'r', label: 'Rook', icon: 'FaChessRook' },
        { name: 'n', label: 'Knight', icon: 'FaChessKnight' },
        { name: 'b', label: 'Bishop', icon: 'FaChessBishop' },
      ];
    case 'end':
      const white = configService.white.split(' ')[0];
      const black = configService.black.split(' ')[0];
      return [
        {
          name: 'w',
          label: white,
          html: SVG_KING,
          custom: html`<style>
            .w svg {
              color: white;
            }
          </style>`,
        },
        { name: 'draw', label: 'Draw', html: SVG_DRAW },
        {
          name: 'b',
          label: black,
          html: SVG_KING,
          custom: html`<style>
            .b svg {
              color: black;
            }
          </style>`,
        },
      ];
    default:
      return [];
  }
}

type ButtonType = {
  name: string;
  label: string;
  icon?: string;
  html?: TemplateResult;
  custom?: TemplateResult;
  type?: string;
};

function getMsg(name: string) {
  switch (name) {
    case 'about':
      return html` <div>
        This chess program is open source and available at github.
        <ul>
          <li>
            <a href="https://github.com/pdigre/chessbuddy" target="_blank" rel="noopener">
              Github pdigre/chessbuddy
            </a>
          </li>
          <li>
            <a
              href="https://github.com/pdigre/chessbuddy/wiki/User-guide"
              target="_blank"
              rel="noopener"
            >
              User Guide / instructions
            </a>
          </li>
        </ul>
      </div>`;
    case 'end':
      return html` <div className="text-3xl">
        Who won?
        <img src="/png/win.png" />
      </div>`;
    default:
      return html`${name}`;
  }
}
