// react/src/Mp4Dialog.tsx
import React from 'react';
import { Dialog, DialogContent, DialogTitle } from '@mui/material';
import { observer } from 'mobx-react';
import { MediaService } from '../../common/service/media.service';
import { action } from 'mobx';

export const Mp4Dialog = observer(({ mp4 }: { mp4: MediaService }) => {
  const width = Math.min(mp4.msg?.width ?? 480, 500);
  return (
    <Dialog
      aria-labelledby="mp4"
      open={mp4.title != undefined}
      onClose={action(mp4.clear)}
      className="text-center text-lg"
    >
      <DialogTitle id="mp4">{mp4.title}</DialogTitle>
      <DialogContent>
        <video id="myVideo" autoPlay={true} width={width}>
          <source src={mp4.msg?.src ?? ''} type="video/mp4" />
        </video>
      </DialogContent>
    </Dialog>
  );
});

// wc/src/mp4dialog.ts
import { MobxLitElement } from '@adobe/lit-mobx';
import { html } from 'lit';
import { customElement } from 'lit/decorators.js';
import { STYLES } from './css';
import { MdDialog } from '@material/web/dialog/dialog';
import { action } from 'mobx';
import { MediaService } from '../../common/service/media.service';

@customElement('cb-dialog-mp4')
export class Mp4Dialog extends MobxLitElement {
  mp4!: MediaService;

  render() {
    new MdDialog();
    const width = Math.min(this.mp4.msg?.width ?? 480, 500);

    return html`
      ${STYLES}
    <md-dialog
      aria-labelledby="mp4"
      .open=${this.mp4.title != undefined}
      @close=${action(this.mp4.clear)}
      class="text-center text-lg">
      <div slot="headline"> id="mp4">${this.mp4.title}</div>>
      <form slot="content">
        <video id="myVideo" autoPlay=${true} width=${width}>
          <source src=${this.mp4.msg?.src ?? ''} type="video/mp4" />
        </video>
      </form>
    </Dialog>
    `;
  }
}
