// react/src/panel-log.tsx
import React, { MouseEvent } from 'react';
import { observer } from 'mobx-react';
import { dashboardService } from '../../common/service/index.service';
import { HistoryService } from '../../common/service/history.service';
import { PlayService } from '../../common/service/play.service';
import { GridWidget } from './main-widgets';
import { action } from 'mobx';

export const PanelLog = observer(
  ({ play, history }: { play: PlayService; history: HistoryService }) => {
    history.enterLogCheck();

    const logClickAction = action((event: MouseEvent<HTMLTableElement>) => {
      event.preventDefault();
      const id = Number.parseInt((event.target as HTMLTableCellElement).id);
      play.undoTo(id === dashboardService.markLog ? -1 : id);
    });

    const viewLog = history.getLogRows().map((row, iRow) => (
      <tr key={iRow} className="[&td]:p-[2px] [&td]:text-left [&td]:text-lg dark:text-white">
        <td className="w-5">
          <span className="text-red-900 text-sm dark:text-red-200">{iRow}</span>
        </td>
        {row.map((col, iCol) => {
          const id = iRow * 2 + iCol;
          const marker = id === dashboardService.markLog ? ' bg-green-300' : '';
          return (
            <td
              id={id.toString()}
              key={id.toString()}
              className={'w-30 p-[2px] text-center text-lg dark:text-white' + marker}>
              {col}
            </td>
          );
        })}
      </tr>
    ));

    return (
      <GridWidget onClickAction={logClickAction} scroll={dashboardService.markLog === -1}>
        {viewLog}
      </GridWidget>
    );
  }
);

// wc/src/panel-log.ts
import { MobxLitElement } from '@adobe/lit-mobx';
import { html } from 'lit';
import { customElement } from 'lit/decorators.js';
import { dashboardService } from '../../common/service/index.service';
import { HistoryService } from '../../common/service/history.service';
import { PlayService } from '../../common/service/play.service';
import { action } from 'mobx';
import { css } from 'lit-element';
import { TW_CSS } from './css.ts';

@customElement('cb-panel-log')
export class PanelLog extends MobxLitElement {
  play!: PlayService;
  history!: HistoryService;

  fingerStart = 0;
  scrollStart = 0;
  scrollMove = 0;
  onTouchStartAction = (event: TouchEvent) => {
    this.fingerStart = event.touches[0].pageY;
    this.scrollStart = this.scrollMove;
    event.preventDefault();
  };
  onTouchMoveAction = (event: TouchEvent) => {
    const fingerMove = this.fingerStart - event.touches[0].pageY;
    this.scrollMove = this.scrollStart + fingerMove;
    //      scrollRef.current?.scroll({ top: scrollMove });
    event.preventDefault();
  };

  clickAction = action((e: MouseEvent) => {
    const target = e.target as HTMLElement;
    if (target.nodeName == 'TD') {
      const i = +target.id;
      dashboardService.setMarkLogAction(i);
      e.preventDefault();
      this.requestUpdate();
    }
  });

  static styles = [
    css`
      table {
        background-color: var(--background-color);
        color: var(--text-color);
      }
      .mark {
        background-color: rgb(134 239 172);
      }
      .td1 {
        width: 1.25rem;
        padding: 2px;
        span {
          color: rgb(127 29 29);
        }
      }
    `,
    TW_CSS,
  ];

  // dashboardService.markLog == -1
  render() {
    this.history.enterLogCheck();

    const logClickAction = (event: MouseEvent) => {
      event.preventDefault();
      const id = Number.parseInt((event.target as HTMLTableCellElement).id);
      this.play.undoTo(id == dashboardService.markLog ? -1 : id);
    };
    const rows = this.history.getLogRows();
    const mark = dashboardService.markLog;
    return html`
      <div class="m-0 p-0 w-full overflow-auto" ref="{scrollRef}">
        <table
          class="m-0 table-fixed w-full"
          @touch-start=${this.onTouchStartAction}
          @touch-move=${this.onTouchMoveAction}
          @click=${this.clickAction}>
          <tbody>
            ${this.renderRows(rows, mark)}
          </tbody>
        </table>
      </div>
    `;
  }
  renderRows(rows: string[][], mark: number) {
    return rows.map(
      (row, iRow) => html`
        <tr>
          <td class="td1 text-lg text-left">
            <span class="text-sm">${iRow}</span>
          </td>
          ${row.map((col, iCol) => {
            const id = iRow * 2 + iCol;
            return html`
              <td id=${id.toString()} class="td text-center text-lg ${id === mark ? 'mark' : ''}">
                ${col}
              </td>
            `;
          })}
        </tr>
      `
    );
  }
}
